[package]
name = "gpx_rust"
version = "0.0.1"
authors = [ "rhn <gihu.rhn@porcupinefactory.org>" ]

[dependencies]
xml-rs = "0.3"
macro-attr = "^0.2.0"
chrono = "0.2"
clap = "2"
#num = "0.1"
gpx_debug = { path = "../gpx_debug" }
quote = "^0.3.8"

